# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# What is the value of the first triangle number to have over five hundred divisors?

import math

number = 7
divisors = 2

while (divisors <= 500):
	number += 1
	triangleNumber = number*(number+1)/2
	divisors = 2
	for i in range(2, int(math.sqrt(triangleNumber)) + 1):
		if (triangleNumber % i == 0):
			divisors += 2
	
print(triangleNumber)